feat: adds Logo component
Math-random-javascript-community/portal pull request #12
Opened 2021-03-01 12:44 UTC by OlegSymonchuk

2021-03-01 14:46 UTC, kucherenko approved these changes

2021-03-16 11:14 UTC, kucherenko requested changes

2021-03-16 11:14 UTC, kucherenko commented on components/common/Logo/Logo.interface.tsx
> +export interface LogoProps {
ts not tsx

2021-03-16 11:14 UTC, kucherenko commented on components/common/Logo/Logo.tsx
> +  '#0687FF',
colors should be in single global place

2021-03-17 18:07 UTC, OlegSymonchuk commented on components/common/Logo/Logo.interface.tsx
> +export interface LogoProps {
Done

2021-03-17 18:07 UTC, OlegSymonchuk commented on components/common/Logo/Logo.tsx
> +  '#0687FF',
Moved

2021-03-17 20:37 UTC, kucherenko approved these changes

2021-03-17 20:37 UTC, merged